import { Enum } from "cc";

export enum GameEvent {
	NONE,

	REGISTER_BUTTON = 10,
	UNREGISTER_BUTTON = 11,

	CAMERA_TRANSITION = 20,
	CAMERA_SHAKE = 21,
	CAMERA_GET = 22,
	CAMERA_UI_GET = 23,
	CAMERA_UPDATE_POSITION = 24,
	CAMERA_FOCUS = 25,

	PATH_UPDATE_POINTS = 30,

	INPUT_START = 100,

	UPDATE_REFLECTION = 200,
	UPDATE_MAX_DISTANCE = 201,
	RAY_HIT_RECEIVED = 202,
	RAY_HIT_SUCCESS = 203,

	
}

Enum(GameEvent);