import { Enum } from "cc";

export enum GameEvent {
	NONE,

	REGISTER_BUTTON = 10,
	UNREGISTER_BUTTON = 11,

	CAMERA_TRANSITION = 20,
	CAMERA_SHAKE = 21,
	CAMERA_GET = 22,
	CAMERA_UI_GET = 23,
	CAMERA_UPDATE_POSITION = 24,
	CAMERA_FOCUS = 25,

	PATH_UPDATE_POINTS = 30,
	ALLSCREEN_INPUT = 31,

	PAUSE_STARSHIPS = 40,
	RESUME_STARSHIPS = 41,
	LAUNCH_STARSHIP = 42,
	LEVEL_UPDATE = 43,
	REMOVE_SIGNAL = 44,

	GET_MAIN_CAMERA = 100,

	UPDATE_REFLECTION = 200,
	UPDATE_MAX_DISTANCE = 201,
	RAY_HIT_RECEIVED = 202,
	RAY_HIT_SUCCESS = 203,
	RAY_HIT_FAIL = 204,


	BUY_ITEM = 300,
	TOGGLE_OVERLAY = 301,
	ADD_REFLECTOR = 302,
	ADD_AMPLIFIER = 303,
	TRY_ADD_REFLECTOR = 304,
	TRY_ADD_AMPLIFIER = 305,
	
	TOGGLE_PLACER = 310,
	MOVE_PLACER = 311,
	ROTATE_PLACER = 312,
	ATTACH_UI_TO_PLACER = 313,
	UPDATE_UI_POSITION = 314,

	CHECK_PLACE_AVAILABILITY = 320,
	TOGGLE_CHECK_MARK = 321,

	// TODO consider deletion
	PURCHASE_ACCEPT = 330,
	PURCHASE_DENY = 331,
	//
	REQUEST_PURCHASE = 332,

	TOGGLE_ROTATION = 400,
	TOGGLE_MOVEMENT = 401,
	DESTROY_ITEM = 402,

}

Enum(GameEvent);